#!/usr/bin/with-contenv bash

# Create directories
if [ ! -d "/opt/docker" ]; then
  mkdir -p /opt/docker
fi

# Login to Dockerhub
if [ ! -z "${DOCKER_HUB_USERNAME}" ]; then
  docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
fi
